// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FCG.Tests.Bdd.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CadastroDeUsuariosFeature : object, global::Xunit.IClassFixture<CadastroDeUsuariosFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-BR"), "Features", "Cadastro de usuários", "  Como visitante da FIAP Cloud Games\r\n  Quero criar minha conta informando nome, " +
                "e-mail e senha\r\n  Para acessar o catálogo e minha biblioteca de jogos", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CadastroDeUsuario.feature"
#line hidden
        
        public CadastroDeUsuariosFeature(CadastroDeUsuariosFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
  #line hidden
#line 9
    await testRunner.GivenAsync("que a plataforma não possui usuários cadastrados", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CadastroDeUsuario.feature.ndjson", 14);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cadastro público cria uma conta de jogador")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de usuários")]
        [global::Xunit.TraitAttribute("Description", "Cadastro público cria uma conta de jogador")]
        public async global::System.Threading.Tasks.Task CadastroPublicoCriaUmaContaDeJogador()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro público cria uma conta de jogador", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.WhenAsync("eu me cadastro com o nome \"Alice\", o e-mail \"alice@fcg.com\" e a senha \"Senha@123\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 13
    await testRunner.ThenAsync("o cadastro deve ser concluído com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 14
    await testRunner.AndAsync("a conta \"alice@fcg.com\" deve ter o perfil \"Player\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 15
    await testRunner.AndAsync("a conta \"alice@fcg.com\" deve estar ativa", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A senha nunca é guardada em texto aberto")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de usuários")]
        [global::Xunit.TraitAttribute("Description", "A senha nunca é guardada em texto aberto")]
        public async global::System.Threading.Tasks.Task ASenhaNuncaEGuardadaEmTextoAberto()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A senha nunca é guardada em texto aberto", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 18
    await testRunner.WhenAsync("eu me cadastro com o nome \"Alice\", o e-mail \"alice@fcg.com\" e a senha \"Senha@123\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 19
    await testRunner.ThenAsync("a senha armazenada da conta \"alice@fcg.com\" não deve ser \"Senha@123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Senha fora da política de segurança é recusada")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de usuários")]
        [global::Xunit.TraitAttribute("Description", "Senha fora da política de segurança é recusada")]
        [global::Xunit.InlineDataAttribute("Se@1", "menos de oito caracteres", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("senha@abc", "não possui número", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("1234@5678", "não possui letra", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("Senha1234", "não possui caractere especial", "5", new string[0])]
        public async global::System.Threading.Tasks.Task SenhaForaDaPoliticaDeSegurancaERecusada(string senha, string motivo, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("senha", senha);
            argumentsOfScenario.Add("motivo", motivo);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Senha fora da política de segurança é recusada", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 22
    await testRunner.WhenAsync(string.Format("eu me cadastro com o nome \"Alice\", o e-mail \"alice@fcg.com\" e a senha \"{0}\"", senha), ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 23
    await testRunner.ThenAsync("o cadastro deve ser recusado por dados inválidos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 24
    await testRunner.AndAsync("nenhuma conta deve ter sido criada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="E-mail em formato inválido é recusado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de usuários")]
        [global::Xunit.TraitAttribute("Description", "E-mail em formato inválido é recusado")]
        [global::Xunit.InlineDataAttribute("alice", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("alice@fcg", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("alice fcg.com", "8", new string[0])]
        public async global::System.Threading.Tasks.Task E_MailEmFormatoInvalidoERecusado(string email, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("email", email);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("E-mail em formato inválido é recusado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 34
    await testRunner.WhenAsync(string.Format("eu me cadastro com o nome \"Alice\", o e-mail \"{0}\" e a senha \"Senha@123\"", email), ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 35
    await testRunner.ThenAsync("o cadastro deve ser recusado por dados inválidos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 36
    await testRunner.AndAsync("nenhuma conta deve ter sido criada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="E-mail já cadastrado é recusado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de usuários")]
        [global::Xunit.TraitAttribute("Description", "E-mail já cadastrado é recusado")]
        public async global::System.Threading.Tasks.Task E_MailJaCadastradoERecusado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("E-mail já cadastrado é recusado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 45
    await testRunner.GivenAsync("que existe um jogador \"alice@fcg.com\" com a senha \"Senha@123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 46
    await testRunner.WhenAsync("eu me cadastro com o nome \"Outra Alice\", o e-mail \"alice@fcg.com\" e a senha \"Outr" +
                        "a@456\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 47
    await testRunner.ThenAsync("o cadastro deve ser recusado por conflito", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 48
    await testRunner.AndAsync("a plataforma deve ter 1 conta cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="E-mail é normalizado antes de ser gravado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de usuários")]
        [global::Xunit.TraitAttribute("Description", "E-mail é normalizado antes de ser gravado")]
        public async global::System.Threading.Tasks.Task E_MailENormalizadoAntesDeSerGravado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("E-mail é normalizado antes de ser gravado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 50
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 51
    await testRunner.WhenAsync("eu me cadastro com o nome \"Alice\", o e-mail \"  ALICE@FCG.COM  \" e a senha \"Senha@" +
                        "123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 52
    await testRunner.ThenAsync("o cadastro deve ser concluído com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 53
    await testRunner.AndAsync("a conta \"alice@fcg.com\" deve ter o perfil \"Player\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A área administrativa cria uma conta de administrador")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de usuários")]
        [global::Xunit.TraitAttribute("Description", "A área administrativa cria uma conta de administrador")]
        public async global::System.Threading.Tasks.Task AAreaAdministrativaCriaUmaContaDeAdministrador()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A área administrativa cria uma conta de administrador", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 55
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 56
    await testRunner.WhenAsync("um administrador cadastra a conta \"root@fcg.com\" com o perfil \"Administrator\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 57
    await testRunner.ThenAsync("o cadastro deve ser concluído com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 58
    await testRunner.AndAsync("a conta \"root@fcg.com\" deve ter o perfil \"Administrator\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CadastroDeUsuariosFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CadastroDeUsuariosFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
